export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS'
export const LOAD_MOVIE_FAILURE = 'LOAD_MOVIE_FAILURE'

export const LOAD_SIMILAR_SUCCESS = 'LOAD_SIMILAR_SUCCESS'
export const LOAD_SIMILAR_FAILURE = 'LOAD_SIMILAR_FAILURE'