export const LOAD_SHOWS_SUCCESS = 'LOAD_SHOWS_SUCCESS'
export const LOAD_SHOWS_FAILURE = 'LOAD_SHOWS_FAILURE'
export const DELETE_SHOWS_SUCCESS = 'DELETE_SHOWS_SUCCESS'
export const DELETE_SHOWS_FAILURE = 'DELETE_SHOWS_FAILURE'